// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/memo_transfer_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/memo_transfer_service.proto.
 */
export const file_api_v1_memo_transfer_service: GenFile = /*@__PURE__*/
  fileDesc("CiJhcGkvdjEvbWVtb190cmFuc2Zlcl9zZXJ2aWNlLnByb3RvEgxtZW1vcy5hcGkudjEiGgoYRXhwb3J0TWVtb0FyY2hpdmVSZXF1ZXN0In4KGUV4cG9ydE1lbW9BcmNoaXZlUmVzcG9uc2USDwoHY29udGVudBgBIAEoDBIQCghmaWxlbmFtZRgCIAEoCRISCgptZW1vX2NvdW50GAMgASgFEhgKEGF0dGFjaG1lbnRfY291bnQYBCABKAUSEAoId2FybmluZ3MYBSADKAkiKwoYSW1wb3J0TWVtb0FyY2hpdmVSZXF1ZXN0Eg8KB2NvbnRlbnQYASABKAwidQoZSW1wb3J0TWVtb0FyY2hpdmVSZXNwb25zZRIQCghpbXBvcnRlZBgBIAEoBRIPCgdza2lwcGVkGAIgASgFEhMKC2F0dGFjaG1lbnRzGAMgASgFEhAKCHdhcm5pbmdzGAQgAygJEg4KBmVycm9ycxgFIAMoCTKxAgoTTWVtb1RyYW5zZmVyU2VydmljZRKLAQoRRXhwb3J0TWVtb0FyY2hpdmUSJi5tZW1vcy5hcGkudjEuRXhwb3J0TWVtb0FyY2hpdmVSZXF1ZXN0GicubWVtb3MuYXBpLnYxLkV4cG9ydE1lbW9BcmNoaXZlUmVzcG9uc2UiJYLT5JMCHzoBKiIaL2FwaS92MS9tZW1vQXJjaGl2ZTpleHBvcnQSiwEKEUltcG9ydE1lbW9BcmNoaXZlEiYubWVtb3MuYXBpLnYxLkltcG9ydE1lbW9BcmNoaXZlUmVxdWVzdBonLm1lbW9zLmFwaS52MS5JbXBvcnRNZW1vQXJjaGl2ZVJlc3BvbnNlIiWC0+STAh86ASoiGi9hcGkvdjEvbWVtb0FyY2hpdmU6aW1wb3J0QrABChBjb20ubWVtb3MuYXBpLnYxQhhNZW1vVHJhbnNmZXJTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations]);

/**
 * @generated from message memos.api.v1.ExportMemoArchiveRequest
 */
export type ExportMemoArchiveRequest = Message<"memos.api.v1.ExportMemoArchiveRequest"> & {
};

/**
 * Describes the message memos.api.v1.ExportMemoArchiveRequest.
 * Use `create(ExportMemoArchiveRequestSchema)` to create a new message.
 */
export const ExportMemoArchiveRequestSchema: GenMessage<ExportMemoArchiveRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_memo_transfer_service, 0);

/**
 * @generated from message memos.api.v1.ExportMemoArchiveResponse
 */
export type ExportMemoArchiveResponse = Message<"memos.api.v1.ExportMemoArchiveResponse"> & {
  /**
   * ZIP bytes, limited to 128 MiB.
   *
   * @generated from field: bytes content = 1;
   */
  content: Uint8Array;

  /**
   * @generated from field: string filename = 2;
   */
  filename: string;

  /**
   * @generated from field: int32 memo_count = 3;
   */
  memoCount: number;

  /**
   * @generated from field: int32 attachment_count = 4;
   */
  attachmentCount: number;

  /**
   * @generated from field: repeated string warnings = 5;
   */
  warnings: string[];
};

/**
 * Describes the message memos.api.v1.ExportMemoArchiveResponse.
 * Use `create(ExportMemoArchiveResponseSchema)` to create a new message.
 */
export const ExportMemoArchiveResponseSchema: GenMessage<ExportMemoArchiveResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_memo_transfer_service, 1);

/**
 * @generated from message memos.api.v1.ImportMemoArchiveRequest
 */
export type ImportMemoArchiveRequest = Message<"memos.api.v1.ImportMemoArchiveRequest"> & {
  /**
   * ZIP bytes, limited to 128 MiB.
   *
   * @generated from field: bytes content = 1;
   */
  content: Uint8Array;
};

/**
 * Describes the message memos.api.v1.ImportMemoArchiveRequest.
 * Use `create(ImportMemoArchiveRequestSchema)` to create a new message.
 */
export const ImportMemoArchiveRequestSchema: GenMessage<ImportMemoArchiveRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_memo_transfer_service, 2);

/**
 * @generated from message memos.api.v1.ImportMemoArchiveResponse
 */
export type ImportMemoArchiveResponse = Message<"memos.api.v1.ImportMemoArchiveResponse"> & {
  /**
   * @generated from field: int32 imported = 1;
   */
  imported: number;

  /**
   * Existing memo IDs are never overwritten.
   *
   * @generated from field: int32 skipped = 2;
   */
  skipped: number;

  /**
   * @generated from field: int32 attachments = 3;
   */
  attachments: number;

  /**
   * @generated from field: repeated string warnings = 4;
   */
  warnings: string[];

  /**
   * Per-record failures are returned with any completed import counts.
   *
   * @generated from field: repeated string errors = 5;
   */
  errors: string[];
};

/**
 * Describes the message memos.api.v1.ImportMemoArchiveResponse.
 * Use `create(ImportMemoArchiveResponseSchema)` to create a new message.
 */
export const ImportMemoArchiveResponseSchema: GenMessage<ImportMemoArchiveResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_memo_transfer_service, 3);

/**
 * MemoTransferService transfers the authenticated user's notes as portable ZIP files.
 *
 * @generated from service memos.api.v1.MemoTransferService
 */
export const MemoTransferService: GenService<{
  /**
   * ExportMemoArchive exports notes and todos across every personal space.
   *
   * @generated from rpc memos.api.v1.MemoTransferService.ExportMemoArchive
   */
  exportMemoArchive: {
    methodKind: "unary";
    input: typeof ExportMemoArchiveRequestSchema;
    output: typeof ExportMemoArchiveResponseSchema;
  },
  /**
   * ImportMemoArchive validates an archive before importing its records.
   *
   * @generated from rpc memos.api.v1.MemoTransferService.ImportMemoArchive
   */
  importMemoArchive: {
    methodKind: "unary";
    input: typeof ImportMemoArchiveRequestSchema;
    output: typeof ImportMemoArchiveResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_memo_transfer_service, 0);
